; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 921600
lib_deps =
    gin66/FastAccelStepper
    https://github.com/avishorp/TM1637
build_flags =
    '-DWIFI_SSID="${secrets.wifi_ssid}"'
    '-DWIFI_PASS="${secrets.wifi_pass}"'
    '-DTASMOTA_IP="${secrets.tasmota_ip}"'